### ISSUE TITLE
Pascal Triangle using C++

### ISSUE THREAD

**Issue by arinjain373** [shrut1-roy/Hacktoberfest2022#15]
I would like to add code for printing code pascal triangle under Hacktoberfest 2022. Can you please assign it to me @shrut1-roy

**Comment by Laxmikant-Dwivedi** [comment]
Please assigned this to me I will fix this issue

**Comment by shrut1-roy** [comment]
This repo is excluded from the event so contribute in any other repo of mine and i'll merge your PR.
It will be counted in hacktoberfest <3
